/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ga3;

/**
 *
 * @author H4H7X
 */
public class vent extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vent.class.getName());

    /**
     * Creates new form vent
     */
    public vent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtnMens1 = new javax.swing.JButton();
        jbtnMens2 = new javax.swing.JButton();
        jbtnMens3 = new javax.swing.JButton();
        jbtnMens4 = new javax.swing.JButton();
        jbtnMens5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cajas de diálogo");

        jbtnMens1.setText("Mensaje1");
        jbtnMens1.addActionListener(this::jbtnMens1ActionPerformed);

        jbtnMens2.setText("Mensaje2");
        jbtnMens2.addActionListener(this::jbtnMens2ActionPerformed);

        jbtnMens3.setText("Mensaje3");
        jbtnMens3.addActionListener(this::jbtnMens3ActionPerformed);

        jbtnMens4.setText("Mensaje4");
        jbtnMens4.addActionListener(this::jbtnMens4ActionPerformed);

        jbtnMens5.setText("Mensaje5");
        jbtnMens5.addActionListener(this::jbtnMens5ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnMens1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnMens5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnMens2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnMens3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnMens4)
                                .addGap(62, 62, 62))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnMens1)
                    .addComponent(jbtnMens4)
                    .addComponent(jbtnMens3)
                    .addComponent(jbtnMens2))
                .addGap(29, 29, 29)
                .addComponent(jbtnMens5)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnMens1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMens1ActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(
                null,
                "La palabra de paso no es correcta",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jbtnMens1ActionPerformed

    private void jbtnMens2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMens2ActionPerformed
        // TODO add your handling code here:
        int boton = javax.swing.JOptionPane.showConfirmDialog(
                null,
                "¿Desea Continuar?",
                "Colegio DB",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
       
    }//GEN-LAST:event_jbtnMens2ActionPerformed

    private void jbtnMens3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMens3ActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showInputDialog(
                null,
                "Palabra de Paso: ",
                "Colegio DB",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbtnMens3ActionPerformed

    private void jbtnMens4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMens4ActionPerformed
        // TODO add your handling code here:
        Object [] opciones = {"Sí, Gracias",
                              "No, Gracias",
                              "Más..."};
        int n = javax.swing.JOptionPane.showOptionDialog(this,
                "Se ha Solucionado el problema", 
                "Soluciones DB", 
                javax.swing.JOptionPane.YES_NO_CANCEL_OPTION, 
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null, 
                opciones,
                opciones[2]);
        
    }//GEN-LAST:event_jbtnMens4ActionPerformed

    private void jbtnMens5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMens5ActionPerformed
        // TODO add your handling code here:
        Object[] valoresSeleccionables = {"uno", "dos", "tres"};
        java.net.URL imgURL = getClass().getResource("/fjcs.jpg");
        javax.swing.ImageIcon icono = null;
        
        if (imgURL != null){
            javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(imgURL);
            java.awt.Image iconoEscalado = iconoOriginal.getImage().getScaledInstance(
                    70,
                    50,
                    java.awt.Image.SCALE_SMOOTH);
            icono = new javax.swing.ImageIcon(iconoEscalado);
            
        }
        String s = (String)javax.swing.JOptionPane.showInputDialog(null,
                "Seleccione una opción",
                "Lista de valores",
                javax.swing.JOptionPane.PLAIN_MESSAGE,
                icono,
                valoresSeleccionables,
                valoresSeleccionables[1]);
    }//GEN-LAST:event_jbtnMens5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vent().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnMens1;
    private javax.swing.JButton jbtnMens2;
    private javax.swing.JButton jbtnMens3;
    private javax.swing.JButton jbtnMens4;
    private javax.swing.JButton jbtnMens5;
    // End of variables declaration//GEN-END:variables
}

